### PR TITLE
Remove duplicate file causing an issue with go modules

### LINKED ISSUE #552: Duplicate file causes issue with `go mod`
When using `go mod`, two files with the same names except for the case of letter in the name causes an issue when unzipping. 

```
$ go mod tidy
go: finding github.com/FactomProject/factom/wallet latest
go: finding github.com/FactomProject/btcd/btcec latest
go: finding github.com/FactomProject/factomd/common/factoid latest
go: finding github.com/FactomProject/factomd/common/interfaces latest
go: finding github.com/FactomProject/factomd/common/primitives latest
go: finding github.com/FactomProject/factomd/database/mapdb latest
go: finding github.com/FactomProject/factomd/database/hybridDB latest
go: finding github.com/FactomProject/factomd/common/directoryBlock latest
go: finding github.com/FactomProject/factomd/database/securedb latest
go: finding github.com/FactomProject/factomd/database/databaseOverlay latest
go: finding github.com/FactomProject/factomd/common latest
go: finding github.com/FactomProject/factomd/database latest
go: extracting github.com/FactomProject/factomd v5.4.2+incompatible
-> unzip /home/aslevy/go/pkg/mod/cache/download/github.com/!factom!project/factomd/@v/v5.4.2+incompatible.zip: case-insensitive file name collision: "scripts/networks/fourSegments26.txt" and "scripts/networks/foursegments26.txt"
go: finding github.com/FactomProject/factomd/testHelper latest
```
Running a diff of the two files in question it shows they are duplicates.
```
$ cd $GOPATH/src/github.com/FactomProject/factomd
$ diff scripts/networks/foursegments26.txt scripts/networks/fourSegments26.txt
```
This would easily be resolved by removing one of these files.

### PR DESCRIPTION
**Pull request by AdamSLevy**
The file scripts/networks/fourSegments26.txt is a duplicate of
scripts/networks/foursegments26.txt. Since they share the same name
except for capitalization, `go mod` had an issue extracting the package.

Fix #552

### CODE REVIEW

**Comment by carryforward** [comment]
please change this pull request to go to the `FactomProject:FD-888_duplicate_filename` branch.  I don't think github makes it easy to change the target branch, so you might need to make a new pull request.

**Comment by AdamSLevy** [comment]
@carryforward I updated the base branch appropriately.

**Comment by carryforward** [comment]
woah, neat, you taught me something new about github today.  Thank you.

**Comment by carryforward** [comment]
ok, this has been merged into the release candidate branch. 
https://github.com/FactomProject/factomd/tree/FD-821_release_candidate_parchment

**Pull request merged**
