### PR TITLE
Added tests for the filter API

### PR DESCRIPTION
**Pull request by JoshuaBrigati**

### CODE REVIEW

**Comment by carryforward** [comment]
lets not commit 28 MB of logs into the git history.

also fix the golang version update to match the master branch.

**Comment by stackdump** [comment]
I'm interested to use this alongside the replay filter testing FD-828 @carryforward is this set to make it into parchment release ?

**Comment by stackdump** [comment]
@JoshuaBrigati @carryforward  I'm going to pull this branch into my replay filter testing effort
Looks like I'll need to deal w/ some conflicts - but my branch is here https://github.com/FactomProject/factomd/tree/FD-896_replay_filter_testing

**Comment by stackdump** [comment]
Closing this PR - here's the latest branch I'll be pulling into replay filter testing https://github.com/FactomProject/factomd/tree/FD-861_filter_api_M

**Pull request closed without merging**
