### PR TITLE
FD-484 Remove message partitioning code

### PR DESCRIPTION
**Pull request by gornik**
Note: the ParcelHeader remains unchanged to remain compatible with the previous versions, the PartNo and PartTotal fields should be removed at the next network protocol version bump.

Also the application continues to handle PartMessageType messages to be backwards compatible with old clients that send them.

### CODE REVIEW

**Comment by gornik** [comment]
@factom-clay rebased against develop

**Comment by factom-clay** [comment]
To be tested by QA in rollup_071718N

**Comment by stackdump** [comment]
old but still good - will resolve conflicts and get this in

**Comment by stackdump** [comment]
TODO: need to cleanup something broken after the merge 

Running ./peerTest/NetSyncA_test.go  / ./peerTest/NetSyncB_test.go

seeing an error 
```
goroutine 118 [running]:
github.com/FactomProject/factomd/p2p.(*Controller).broadcast(0xc000154780, 0x6000900beaded, 0x181, 0xe00bc6, 0xb, 0xd3d72359, 0x0, 0x0, 0x0, 0xc000450388, ...)
        /home/ork/go/src/github.com/FactomProject/factomd/p2p/controller.go:667 +0x42
github.com/FactomProject/factomd/p2p.(*Controller).route(0xc000154780)
        /home/ork/go/src/github.com/FactomProject/factomd/p2p/controller.go:453 +0x625
github.com/FactomProject/factomd/p2p.(*Controller).runloop(0xc000154780)
        /home/ork/go/src/github.com/FactomProject/factomd/p2p/controller.go:415 +0x101
created by github.com/FactomProject/factomd/p2p.(*Controller).StartNetwork
        /home/ork/go/src/github.com/FactomProject/factomd/p2p/controller.go:201 +0xe1
FAIL    command-line-arguments  2.238s
```

**Comment by PaulBernier** [comment]
p2p package has been entirely replaced by p2p2 in Wax released. Closing.

**Pull request closed without merging**
