### PR TITLE
Jh refault

### PR DESCRIPTION
**Pull request by hannemennah**
Fault Refactoring

### CODE REVIEW

**Comment by hannemennah** [comment]
Commits that can be safely ignored during Fault-specific code-review:

https://github.com/FactomProject/factomd/pull/37/commits/6124768aae2a49df5a7dfc6c5132fc97a76a58cd (debug printing cleanup)
https://github.com/FactomProject/factomd/pull/37/commits/079befff7a3a1fabb8a8377ae83f02a517ac6d6b (debug printing cleanup)
https://github.com/FactomProject/factomd/pull/37/commits/aafd5688ec34036f06b7b0378b00ea0c6afeae7a
(data structure detail printout)
https://github.com/FactomProject/factomd/pull/37/commits/68acdc13c2224585c43569989b8fce5f415214bc (temporary index variable deleted)
https://github.com/FactomProject/factomd/pull/37/commits/1acf9a9e3e5d54504a7a04538b86c0450a31174a (debug printing and comment cleanup)
https://github.com/FactomProject/factomd/pull/37/commits/4bbf12d299b27aaa9026e281bb98c5ca8d756256 (merge of jh-1 into jh-refault, no fault-relevant changes)
https://github.com/FactomProject/factomd/pull/37/commits/738dd26ed5bdaf827a77ee1df4aec417def4fc92 (data structure detail printout)
https://github.com/FactomProject/factomd/pull/37/commits/c9230073f02702e9ca46e90d8698de7bb66357d4 (deleting old, unreferenced code)
https://github.com/FactomProject/factomd/pull/37/commits/bd6a44e38463573bbf9c0993a29cdd94df4a3e69 (Paul's change, minor timeout tweak, no fault-relevant changes)
https://github.com/FactomProject/factomd/pull/37/commits/e1a1a82743f523f4271914afc103146689c20517 (Paul's change, dbheight tweak in ProcessBlocks, no fault-relevant changes)

**Comment by hannemennah** [comment]
Commits that have relatively-minor, easy-to-summarize changes which *do* affect Faulting:

https://github.com/FactomProject/factomd/pull/37/commits/be9ded1aaeab1e43c14751d5d4f1f93196b740da : this commit is a "large" diff, though the logic of the function (ProcessFullServerFault) should ultimately be basically-unchanged. It is an attempt to consolidate the code-paths and simplify the logic by breaking out some of the nested-if logic. Behavior should not be materially affected, just (hopefully) code readability.

https://github.com/FactomProject/factomd/pull/37/commits/bf077b2e0a49fc9a8187605b4ca8bdd0cd6784c6 : when a Leader is replaced by an Audit server, set the newly-demoted Leader to "offline" so that it isn't the top choice for any upcoming elections

https://github.com/FactomProject/factomd/commit/3b7ca9eadc2fa74da6160fa1152c5b04d83d90cf : when deciding whether to fault the next VM, check to make sure you wouldn't be faulting yourself (which never makes sense)

https://github.com/FactomProject/factomd/pull/37/commits/fd54686a4992e52a3dda08eafabe17bcf605850c : when a FullFault has been processed successfully, set LastFaultAction = current time (to make sure subsequent faulting doesn't occur too quickly afterwards, and there is a minimal length of time for the network to recover/proceed)

https://github.com/FactomProject/factomd/pull/37/commits/704be7f2573406b1224e7653f87de0acf46b2dae : rather than doing complicated Fault-timeouts, just wait the standard length of time (default 20 seconds) before timing out a particular ongoing negotiation

https://github.com/FactomProject/factomd/pull/37/commits/b4e4ba648405a0ec8b5d981aea51e929f6d020d2 : make sure that the "AmINegotiator" boolean is updated consistently during the Faulting process

https://github.com/FactomProject/factomd/pull/37/commits/26839f1ee92def21f77c2a3c777fedf0e3356e29 : once a particular FullFault message has been validated (whether it is complete-and-executable or incomplete), it does not need to be redundantly validated, so we now mark it with an "alreadyValidated" boolean (which is not marshalled with the message) to keep track of this and prevent overvalidating

https://github.com/FactomProject/factomd/pull/37/commits/2ff971d7a257c9380b7f61e734a738ddde8233d8 : once a particular FullFault message has been processed (whether it is complete-and-executable or incomplete), it does not need to be redundantly processed, so we now mark it with an "alreadyProcessed" boolean (which is not marshalled with the message) to keep track of this and prevent overprocessing

https://github.com/FactomProject/factomd/pull/37/commits/f7a571c528c09a334c335b4dddc4f41f21064af0 : when issuing a renewal for a particular negotiation-cycle (starting over with a new FullFault message after a timeout period elapses), do not use the same Audit server for the next renewal if the old one never pledged successfully -- in other words, "cycle" through available Audit servers when the top-choice fails to pledge

https://github.com/FactomProject/factomd/pull/37/commits/bbbf83a60ab839de3c0feac67d2ce746a5d6958a : most of this commit is cleanup (removing old, unreferenced code), but a new field is added to FullFault messages called "ClearFault" -- a boolean intended to represent whether the fault can be ignored (i.e. the faulted server came back online before the negotiation process terminated)

https://github.com/FactomProject/factomd/pull/37/commits/e776fe98704e5c92cd8095eef946ce3924966067 : this commit replaces our "FaultMap" with a single "CurrentFault" that we keep track of (rather than a full map of faults). This will force nodes to "choose" which fault they consider top priority at any given time, and simplify analysis in the long-term. Most of the changes are simply removing map-specific getters/setters and references.

https://github.com/FactomProject/factomd/pull/37/commits/39a3b7e4abc2df3cb89dc831c3824d88e4f0420e : this commit should be obsolete by now, due to the changes made in e776fe98 (because it was an attempt at cleaning up the FaultMap)

**Comment by hannemennah** [comment]
https://github.com/FactomProject/factomd/pull/37/commits/b09ddbefd30e7aab3eece9b346064056fa3a76b2 : a substantial portion of this commit is removing old, unreferenced code (and commentary). The "ToggleAuditOffline" behavior has been broken out to be a function of its own. There are some changes made to when "AmINegotiator" is set, but all of these were superceded by the changes in the commit b4e4ba648 (which came 11 days later). Other than that, superficial "tagging" was added to Faulting (which doesn't affect actual runtime behavior, just helps with debugging) and a sanity Nil-check was added. This commit was largely cleanup (as the message indicates).

https://github.com/FactomProject/factomd/pull/37/commits/e7f2727046932e1df0059251247f57d959b499b4 : this adds "ClearFault" functionality (making use of the boolean field introduced in commit bbbf83a60) to allow servers that were considered at-fault to come back online during a negotiation process; there is also (very minor) cleanup of now-unused code

https://github.com/FactomProject/factomd/pull/37/commits/71ef19b2ec11ed629ead5f496daa9460107ba7c1 : keep track of *why* a server was faulted (because an EOM fault can be cleared by issuing the missing EOM, but a negotiation-initiated fault cannot); for the same reasons, superficial (debug) tagging functionality is added to the "markFault" function. The default FaultWait timeout (for reissuing negotiation messages) is reduced from 5 seconds to 3 seconds for more reliable negotiation proceedings.

https://github.com/FactomProject/factomd/pull/37/commits/cf9f6c53364213de5f3961feba48de3011af401d : allow incomplete FullFault messages to be added to the SystemList, so they can have process-attempts executed on them like any other type of message (fitting into the known-to-be-good validator-loop model). This meant moving logic that used to be checking for validity in the Validate() function into ProcessFullFault instead. Prior to this, only fully-complete FullFault messages were allowed into the SystemList, which basically meant anything in the SystemList is instantly executed. 

https://github.com/FactomProject/factomd/pull/37/commits/e622ba415730b7e6d1d6622004e91aa919e31002 : the NewAllClear() function is deleted, since it was never used (and generally not-useful). The "markFault" and "markNoFault" functions are introduced, which are the general-purpose functions for servers to keep track of who is at-fault on the network at any given moment. The NegotiationCheck() function is also introduced, which is the function that causes a Negotiator to send out their negotiation messages periodically when necessary. The FaultCheck() function is also introduced, which is how Leaders are able to keep track of whether a negotiation process has failed (so that the negotiator can be faulted). The "WhenFaulted" field on VMs is updated to be externally-referencable, for Status output simplicity.

**Comment by n1rvana** [comment]
Merging as review looks good.

**Pull request merged**
